name: 'Setup Bun Project'
description: 'Setup Bun and install dependencies (requires checkout first)'

inputs:
  bun-version:
    description: 'Bun version to install'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Install Dependencies
      shell: bash
      run: bun install