blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question
    url: mailto:nowarajs@pm.me
    about: |
      If you have a question about the project, please feel free to reach out. 
      I will do my best to respond as soon as possible.