name: Lint

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        type: string
    secrets:
      KEY_SSH:
        required: true
      KEY_GPG:
        required: true
      GIT_EMAIL:
        required: true

jobs:
  lint:
    name: Check Lint (try to auto-fix if possible)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          ssh-key: ${{ secrets.KEY_SSH }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Lint and try to auto-fix if possible
        id: lint_step
        run: |
          if bun run lint; then
            echo "lint_status=clean" >> $GITHUB_OUTPUT
          else
            bun run fix-lint
            if bun run lint; then
              echo "lint_status=fixed" >> $GITHUB_OUTPUT
            else
              echo "lint_status=failed" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Import GPG key and configure git
        if: steps.lint_step.outputs.lint_status == 'fixed'
        run: |
          echo "${{ secrets.KEY_GPG }}" | gpg --batch --import
          git config --local user.signingkey "$(gpg --list-keys --with-colons | grep '^pub' | cut -d':' -f5 | head -n1)"
          git config --local commit.gpgsign true
          git config --local tag.gpgsign true
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "github-actions"

      - name: Commit Changes
        if: steps.lint_step.outputs.lint_status == 'fixed'
        run: |
          if git diff --name-only | grep -E '\.(js|ts|jsx|tsx|css|scss|json|md|yml|yaml)$'; then
            git add .
            git commit -m "style(🎨): Auto-fix lint issues"
          else
            echo "No lint-related changes to commit."
          fi

      - name: Push changes
        if: steps.lint_step.outputs.lint_status == 'fixed'
        run: |
          git push origin HEAD:${{ inputs.branch }}